### ISSUE TITLE
Passing bindings to a component

### ISSUE THREAD

**Issue by albertosantini** [WebReflection/introspected#3]
Imagine the need to pass something to a component (values, objects or functions): they are the bindings of that component.

In this primitive example of a modal dialog, I use a flag to show the modal and, when the modal is closed, some info is returned and the flag is set to false to hide the modal.

Notes:
- I pass the whole state, as bindings, to the "child" component, and not a slice of the state: I need only `openBarModal` and `closeBarModal`.
- I use `observe` api to add another handler to the state, rendering the "child" template, when the state (bindings) changes, 

Concerns:
- Do you think this bindings practice is feasible?
I am trying to reproduce this kind of approach (in AngularJS):
```
<token-dialog open-modal="$ctrl.openTokenModal"
    close-modal="$ctrl.closeTokenDialog(tokenInfo)">
</token-dialog>
```

- The dialog is not closed after pressing "Close Bar Dialog" button, even if `state.openBarModal` is set to `false` in `onCloseBarModal`.

The caller `Foo component`, in the template:
```
            <button id="openBarDialog" type="button"
                onclick="${() => {
                    state.openBarModal = true;
                }}">Open Bar Dialog
            </button>
```

and in the controller:
```
        this.state = Introspected({
            items,
            selectedItem: items[1],
            toggleList: true,
            openBarModal: false,
            closeBarModal: this.onCloseBarModal
        }, state => template.update(render, state, events));

        BarComponent.bootstrap(this.state);
...

    onCloseBarModal(res) {
        this.state.openBarModal = false;
        console.log(res);
    }
```

The callee `Bar Component`:

```
// bar.controller.js
class BarController {
    constructor(render, template, bindings) {
        Introspected.observe(bindings,
            state => template.update(render, state));
    }
}

// bar.component.js
class BarComponent {
    static bootstrap(bindings) {
        const render = hyperHTML.bind(Util.query("bar-dialog"));


        this.barController = new BarController(render, BarTemplate, bindings);
    }
}

// bar.template.js
class BarTemplate {
    static update(render, state) {
        if (!state.openBarModal) {
            return;
        }

        render`
...
                        <button id="closeBarDialog" type="button"
                            onclick="${() => {
                                state.closeBarModal({ answer: "BarModal closed" });
                            }}">Close Bar Dialog
                        </button>
...
```

- How to reproduce the issue: press "Open Bar Dialog", the dialog is displayed, then press "Close Bar Dialog" and the dialog is not closed, even if `onCloseBarModal` is called correctly (there is the log in the console).

The complete live example: https://plnkr.co/edit/YwsHHSvjpDx1uXfQwTA5?p=preview

**Comment by WebReflection** [comment]
I haven't tested yet but there is a fundamental issue in this approach: you are using non serializable data  through the state.

A state with a method? That smells, it's not a state anymore, rather a controller.

Do not use anything different from object, array, string, boolean, number, an d null for the state, and use the path information to eventually react to changes.

On top of that mistake, there is also another mistake: you are passing a class method to the state without binding it.

`closeBarModal: this.onCloseBarModal`

that one, should be

`closeBarModal: this.onCloseBarModal.bind(this)`

but we are back to the issue: you should really try to avoid methods and functions in a state or you easily fall into anti-patterns like the method that wasn't bound, and you cannot freeze and resurrect a state if not fully serializable.

**Comment by albertosantini** [comment]
This one works correctly: https://plnkr.co/edit/wAwHNpeTb0bGUMy7cAGV?p=preview

The difference w.r.t. the previous one:
- Moved `state.openBarModal = false;` in BarTemplate / close onclick
- Reset the modal template, when I close it, with 
```
render`${hyperHTML.wire()``}`
```


A bit artificial, but it works.

- Notes about rendering.

I thought to call the update of main template and to call the update of modal dialog, when `openBarModal` is true; hence the observe call on the state in the modal controller, adding the rendering of the modal. 

So when `openBarModal` is false, I thought only the main template was rendered, and not the modal one. Apart the error where to set that variable (first point above), it worked in that way, but the modal template was not "closed".

It is not "closed" not because it is rendered again, indeed the conditional part (in Bar template) works correctly, but because the previous rendering is not removed from the dom.

So the question is more related to hyperHTML realm than Introspected one for this part (see the reset point above, the artificial workaround).

- Notes about functions in the state.

I would like to pass callbacks to the child component.
At the beginning I separated `state` and `bindings`, like 

```
// in the template
static update(render, state, bindings) {
...

// in the controller
Introspected.observe(bindings,
            state => template.update(render, state, bindings));
...
```

But that seems a rabbit hole more than a solution.

I didn't found any concern about the functions without a context (without `.bind`), because the functions are used like callbacks.

**Comment by albertosantini** [comment]
Ok, it seems I resolved passing `events` until the modal, so we don't have any function in the state and it is coherent with the rest of the controllers in terms of state and events.

```
// in the main Foo controller
        this.state = Introspected({
            items,
            selectedItem: items[1],
            toggleList: true,
            openBarModal: false,
            answerBarModal: ""
        }, state => template.update(render, state, events));

        BarComponent.bootstrap(this.state, events);
...

// in the Bar modal component
        this.barController = new BarController(render, BarTemplate, state, events);
...

// in the Bar modal controller
class BarController {
    constructor(render, template, bindings, events) {
        Introspected.observe(bindings,
            state => template.update(render, state, events));
    }
}
...

// in the Bar modal template
                            onclick="${e => {
                                state.openBarModal = false;
                                events(e, { answer: "BarModal closed" });
                            }}">Close Bar Dialog


```
Live demo: https://plnkr.co/edit/F4xP7mQSAVIQwOFjIfTR?p=preview

**Comment by WebReflection** [comment]
It's a very big example and I'm lost in what's the problem exactly.

Can you please write the most minimal case ever to reproduce the issue, if there is an issue?

Thanks

**Comment by albertosantini** [comment]
Removing parts would hide the powerful features of the lib. 
It is nice to see how the list is updated when the modal is displayed. :)

Joking apart, I recap the concerns.

- [resolved] How to pass bindings to a component? Separating the bindings in terms of state and events, and passing them accordingly.

- [half resolved] How to pass a part of the state to the component? At the moment I pass the whole state to the modal, but it would be nice passing only the relevant part. I cannot use two Introspected objects, two states, because I need to modify the same property in different templates.
```
        // this works if bindings is this.state, 
        // but correctly it doesn't, if it is this.state.openBarModal
        Introspected.observe(bindings,
            state => template.update(render, state, events));
```

- [resolved] How to empty a template? Using an empty wire, useful to remove conditionally a template from the dom.
```
render`${hyperHTML.wire(render, ":empty")``}`;
```

**Comment by WebReflection** [comment]
> How to pass a part of the state to the component? At the moment I pass the whole state to the modal, but it would be nice passing only the relevant part.

This bit I don't understand. You can pass any sub-property of an introspected state to anything you want. You'll even be notified by updates, and you can use the path passed along to understand which bit should be updated or not.

Moreover, updates in hyperHTML are cheap, even of a whole app. The DBMonster table should demonstrate you should never worry about updating more, it's already deadly fast and you would rarely hit any performance issue updating a bigger page.

**However**, you could partially update if needed, but I need to see a simple example of the issue you are facing or I won't be able to help.

> How to empty a template?

The following should do as well
```js
render`${[]}`;
```

Although in general, that works only if the whole render passes through the same template literal, which is an emty surrounding strings in that case.

Example: if you had this 

```js
render`a ${[]} b`;
```

and you do this
```js
render`${[]}`;
```

The bound context of the render function will be upgraded again from scratch (but not its internal wires).

Does it make sense?

**Comment by albertosantini** [comment]
> This bit I don't understand. You can pass any sub-property of an introspected state to anything you want. 

It is not the use case of passing a sub-property and updating it.
That works nicely and the changes are automagically propagated.

Opening a new issue with a tiny example getting Type Errror.

> The bound context of the render function will be upgraded again from scratch (but not its internal wires).

It makes sense, I hope. :)
