### ISSUE TITLE
How to render the template only if a sub-property of state is updated?

### ISSUE THREAD

**Issue by albertosantini** [WebReflection/introspected#4]
I am trying to update a template using a sub-property of another state.

```
"use strict";

const render = hyperHTML.bind(document.querySelector("root"));
const render2 = hyperHTML.bind(document.querySelector("root2"));
const render3 = hyperHTML.bind(document.querySelector("root3"));

// The usual state
const state = Introspected({
    catalogName: "Default Catalog",
    items: ["item1", "item2"]
}, s => {
    render`<h1>${s.catalogName}</h1>
        <ul>${s.items.map(item => `<li> ${item} </li>`)}</ul>
    `;
});

// Add another rendering to the same state
Introspected.observe(state, s => {
    render2`<h1>Another ${s.catalogName}</h1>
        <ul>${s.items.map(item => `<li> ${item} </li>`)}</ul>
    `;
});

setTimeout(() => {
    state.catalogName = "Default Catalog Updated"; // updating only root1, root2
}, 1000);

// Trying to add another rendering to a partial state,
// intending to update the template only if state.items change
Introspected.observe(state.items, s => {
    render3`<h1>Other Catalog</h1>
        <ul>${s.items.map(item => `<li> ${item} </li>`)}</ul>
    `;
});

setTimeout(() => {
    state.items.push("item3"); // updating root1, root2 and root3
}, 1000);
```

Live demo: https://plnkr.co/edit/IjZF042kY84L3fOGASe3?p=preview

**Comment by albertosantini** [comment]
The error is expected.

How to render `root3` only if a sub-property of `state` is updated?

**Comment by WebReflection** [comment]
this ticket title is confusing, there's no JSON involved in here. Can you please edit it?

> How to render root3 only if a sub-property of state is updated?

You keep ignoring the path variable.

The introspected is the state, and indeed you receive the state in the callback, not its items so ... stick with it.

```js
Introspected.observe(state, (s, path) => {
    if (path[0] === 'items') {
      render3`<h1>Other Catalog</h1>
        <ul>${s.items.map(item => `<li> ${item} </li>`)}</ul>
      `;
    }
});
```

You are basically observing changes and acting only if anything inside the items property was changed, ignoring any other update outside such property.

You can easily automate this pattern, or propose an utility to do that.

I might consider simply accepting an intermediate path while observing.

```js
// API example
Introspected.observe(state[, path?], callback);

// your case
Introspected.observe(state, ['items'], s => render`${s.items}`);
```

**Comment by albertosantini** [comment]
My concern about using path is the isolation of the component.

I am not convinced `path` resolves it.

That `Introspected.observe` is inside another component, different from the component, owner of the original state. 

I would like it worked `Introspected.observe(subState)` and `subState` is the subset of the original state passed to the component.

Something like
```
// this is done in component 1
const subState = Introspected(state, ['items']); 
...
// this is in component 2, receiving subState from component 1
Introspected.observe(subState, callback); 
```

If `items` is updated, `component1` and `component2` are updated.

**Comment by WebReflection** [comment]
the problem is that if you change the subState in component 2, you want state in component 1 to be notified too.

Only way to go is to make subState trigger 2 callbacks, one before without being notified, and one for itself, branching out from the loop.

This might cause backfiring issues, in case the root component changes subState when it triggers ... hence my initial decision to have one source of truth on the root.

I'll think about it though, I see value in having this behavior too. I just want to avoid blowing too much the lib or its complexity for simpler use cases where you don't share a state between different components.

**Comment by albertosantini** [comment]
On a second thought and reading your last notes, I think the status quo (and using the path) is enough.

I would return again on these thoughts, when I completed the migration wit more insights.

> I just want to avoid blowing too much the lib or its complexity for simpler use cases where you don't share a state between different components.

Totally agreed.

**Comment by WebReflection** [comment]
although ... there are still few stars and you are the most active user here, testing for real this project.

I am thinking to do a massive refactoring of this library in order to support subPath notifications.

At the end of the day, it is what I would expect too, passing through `Introspected.observe(introspected.any.subPath, callback)`

This lib is full of Proxy magic, why not making it fully wicked at this early stage?

Let's see how it goes.

**Comment by albertosantini** [comment]
This is an interesting use case where observing `subPath` would be something `nice to have`.

```
class LiBazElement extends Hyper {
    constructor() {
        super();

        this.events = (e, payload) => Util.handleEvent(this, e, payload);
        this.items = FooService.getItems();
        this.state = this.items[this.dataset.id - 1];
    }

    render() {
        return LiBazTemplate.update(this.hyper, this.state, this.events);
    }

    onLibazClick() {
        const oldValue = this.state.text;

        this.state.text = "hey li-baz";
        setTimeout(() => {
            this.state.text = oldValue;
            this.render();
        }, 500);
        this.render();
    }
}
customElements.define("li-baz", LiBazElement);
```

If we need to render `li-baz` component, when an item of the Introspected object `state.items` is updated or just to avoid to call explicitly the render method, it would be nice to have the following `observe`:

```
class LiBazElement extends Hyper {
    constructor() {
        super();

        this.events = (e, payload) => Util.handleEvent(this, e, payload);
        this.items = FooService.getItems();
        this.state = this.items[this.dataset.id - 1];

        Introspected.observe(this.items, this.render); // NEW LINE
    }

    render() {
        return LiBazTemplate.update(this.hyper, this.state, this.events);
    }

    onLibazClick() {
        const oldValue = this.state.text;

        this.state.text = "hey li-baz";
        setTimeout(() => {
            this.state.text = oldValue;
        }, 500);
        // REMOVED RENDER CALLS
    }
}
customElements.define("li-baz", LiBazElement);
```

I vote for 

`Introspected.observe(introspected.any.subPath, callback)`

instead of

`Introspected.observe(state[, path?], callback);`

because we are not passing the whole state to the services.
