### ISSUE TITLE
Empty proxy with new Date

### ISSUE THREAD

**Issue by albertosantini** [WebReflection/introspected#5]
Is it expected an empty proxy, without properties, with a `Date` object?

```
const x = Introspected({
  toasts: [
    { date: new Date(), message: "now" }
  ]
});

// display empty proxy and "now"
console.log(x.toasts[0].date, x.toasts[0].message);
```

Live demo: https://plnkr.co/edit/Uklm1tJFSgxXf8oqkFHi?p=preview

**Comment by WebReflection** [comment]
nope, I forgot about Date

**Comment by WebReflection** [comment]
Solved in `0.2.2`

**Comment by albertosantini** [comment]
Thanks a lot (but it is not published). :)

(At the moment I replaced the toasts component and it is seamlessly used in AngularJS components).

**Comment by WebReflection** [comment]
it is published now, sorry :smiley:
