### ISSUE TITLE
Uncaught TypeError: 'deleteProperty' on proxy: trap returned falsish for property 'a'

### ISSUE THREAD

**Issue by albertosantini** [WebReflection/introspected#6]
From MDN about the return value of delete:

`true for all cases except when the property is an own non-configurable property, in which case, false is returned in non-strict mode.`

It seems expected, but I don't know how to empty the state or if it is an anti-pattern.

```
"use strict";

const state = Introspected({
    a: 1,
    b: 2
});

for (let prop in state) {
  delete state[prop];
}  

// Uncaught TypeError: 'deleteProperty' on proxy: trap returned falsish for property 'a'
```

Live demo: https://plnkr.co/edit/PuRseujyYxOGQbniXVZC?p=preview

**Comment by WebReflection** [comment]
so, if I understand correctly, I need to return true even on delete?

**Comment by albertosantini** [comment]
Well, I don't care about the return value.

The aim is deleting the property.

Indeed, as workaround, I inserted that kind of code in a try/catch, ignoring the exception.

**Comment by WebReflection** [comment]
`v0.2.3` is out
