### ISSUE TITLE
Uncaught TypeError: target.toJSON is not a function

### ISSUE THREAD

**Issue by albertosantini** [WebReflection/introspected#8]
I simplified a use case I have in my code.

From the console of the live test page:
```
x = Introspected({arr: []})
Proxy {arr: Array(0)}

Introspected.observe(x.arr, () => {})
Uncaught TypeError: target.toJSON is not a function
    at Function.Introspected [as observe] (introspected.js:179)
    at <anonymous>:1:14

Introspected.observe(x.arr)
[copyWithin: ƒ, fill: ƒ, pop: ƒ, push: ƒ, reverse: ƒ, …]
```

Is it expected? Am I missing anything?

**Comment by WebReflection** [comment]
I haven't touched this repo in ages ... and I am not planning to change anything in here for a while (busy with hyperHTML refactoring at the moment)

what is it that is not working?
was it working before?
any idea what could cause the issue?

and so on :smiley:

**Comment by albertosantini** [comment]
I was following [this approach](https://github.com/WebReflection/introspected/issues/4#issuecomment-303822595), described in another issue, to trigger the callback when I have a state with nested Introspected objects.

The pattern is modifying the Introspected object inside the callback of the `observe` method of the nested Introspected object just to trigger the "main" callback.

As we talked in the other issue, this doesn't work, meaning the callback is not fired:
`this.state.ohlcInfo.feed = QuotesService.getQuotes();`

So a feasible way to resolve it, at least for me, is the following approach: 

``` javascript
Introspected.observe(QuotesService.getQuotes(), state => {
    if (JSON.stringify(state) !== "{}") {
        this.state.ohlcInfo.feed = JSON.stringify(state.quotes[this.state.selectedInstrument]);
    }
});
```

It works for objects, but not for arrays:

``` javascript
x = Introspected({obj: {}})
Proxy {obj: Proxy}
Introspected.observe(x.obj, () => {})
Proxy {}
```

Indeed the offending line in Introspected is the following one (179):
`known.get(target.toJSON()).O.$.add(callback);`

And `target`, an array, has not `toJSON` method.

**Comment by WebReflection** [comment]
beside the bug, this check is wrong for many reasons
```js
JSON.stringify(state) !== "{}"
```

what you want there is:
```js
if (Object.keys(state).length) { ...
```

Moreover, the `toJSON` is intercepted by the Proxy
https://github.com/WebReflection/introspected/blob/master/introspected.js#L76

if your array has no `toJSON` it means it's not a Proxy

**Comment by albertosantini** [comment]
Thanks for the tip `Object.keys(state).length`.

Investigating about Proxy reference.
I think I checked it, but I double check that.

**Comment by albertosantini** [comment]
Just a moment. :)

My steps to reproduce the issue are the following:
- `x = Introspected({arr: []})`
- `Introspected.observe(x.arr, () => {})` // exception

Indeed `x` is a Proxy and `x.arr` is an Array (in the example above and `in my code`).

Of course with the workaround `{ arr: { value: [ ] } }` is ok.
- `x = Introspected({ arr: { value: [ ] } }, () => {})`
-  `Introspected.observe(x.arr, () => {})` // ok

So it is not a bug, but a grey zone. :)

The point (I was missing, as usual) is the difference between `creating` the Introspected object (the Proxy object), containing an array, and `extracting` that array. 

I don't know if this diff is expected, intending objects are returned, if accessed, as Proxy and arrays as Array, but I can live with it.

If it makes sense for you, I can close the issue.

**Comment by WebReflection** [comment]
this project is far away from my priority list and it works for what it's meant to do ... it can be improved with branched proxies but that's a whole new world of mess I have zero time to deal with these days.

closing for now, sorry if that's not the best outcome.

**Comment by albertosantini** [comment]
No problem.

`Introspected` is legacy. :)

When the code lands in the master, because the app is working, I intend to refactor the app using `hyper.Component` and `setState` approach.

**Comment by WebReflection** [comment]
no legacy, I just have other priorities now

**Comment by albertosantini** [comment]
Well, legacy for me, because I started the refactoring in May. 

Nice to know about the priorities.
